syntax = "proto3";
package plugnmeet;

option go_package = "github.com/mynaparrot/plugnmeet-protocol/plugnmeet";
option php_namespace = "Mynaparrot\\PlugnmeetProto";

message CreateBreakoutRoomsReq {
  string room_id = 1;
  string requested_user_id = 2;
  uint64 duration = 3;
  optional string welcome_msg = 4;
  repeated BreakoutRoom rooms = 5;
  optional WhiteboardShare whiteboard_share = 6;
  optional PollShare poll_share = 7;
  bool share_notepad = 8;
  bool allow_return_to_main_room = 9;
  bool allow_self_select = 11;
}

message BreakoutRoom {
  string id = 1;
  string title = 2;
  uint64 duration = 3;
  bool started = 4;
  uint64 created = 5;
  repeated BreakoutRoomUser users = 6;
  string room_sid = 7;
}

message BreakoutRoomUser {
  string id = 1;
  string name = 2;
  bool joined = 3;
}

message IncreaseBreakoutRoomDurationReq {
  string breakout_room_id = 1;
  uint64 duration = 2;
  string room_id = 3;
}

message BroadcastBreakoutRoomMsgReq {
  string msg = 1;
  string room_id = 2;
}

message JoinBreakoutRoomReq {
  string breakout_room_id = 1;
  string user_id = 2;
  string room_id = 3;
}

message EndBreakoutRoomReq {
  string breakout_room_id = 1;
  string room_id = 2;
}

message ReInviteBreakoutRoomReq {
  string breakout_room_id = 1;
  string user_id = 2;
  string room_id = 3;
}

message BackToMainRoomReq {
  string room_id = 1;
  string user_id = 2;
  string parent_room_id = 3;
}

message BreakoutRoomRes {
  bool status = 1;
  string msg = 2;
  optional string token = 3; // join token
  optional BreakoutRoom room = 4; // for my breakout room
  repeated BreakoutRoom rooms = 5; // rooms list
}

message WhiteboardShare {
  string file_id = 1;
  repeated uint32 pages = 2;
  uint32 current_page = 3;
}

message BackToMainRoomRes {
  bool status = 1;
  string msg = 2;
  optional string token = 3; // main room access token
}

message PollShare {
  repeated string poll_ids = 1;
}
