// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: plugnmeet_analytics.proto

package plugnmeet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyticsEventType int32

const (
	AnalyticsEventType_ANALYTICS_EVENT_TYPE_ROOM AnalyticsEventType = 0
	AnalyticsEventType_ANALYTICS_EVENT_TYPE_USER AnalyticsEventType = 1
)

// Enum value maps for AnalyticsEventType.
var (
	AnalyticsEventType_name = map[int32]string{
		0: "ANALYTICS_EVENT_TYPE_ROOM",
		1: "ANALYTICS_EVENT_TYPE_USER",
	}
	AnalyticsEventType_value = map[string]int32{
		"ANALYTICS_EVENT_TYPE_ROOM": 0,
		"ANALYTICS_EVENT_TYPE_USER": 1,
	}
)

func (x AnalyticsEventType) Enum() *AnalyticsEventType {
	p := new(AnalyticsEventType)
	*p = x
	return p
}

func (x AnalyticsEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnalyticsEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugnmeet_analytics_proto_enumTypes[0].Descriptor()
}

func (AnalyticsEventType) Type() protoreflect.EnumType {
	return &file_plugnmeet_analytics_proto_enumTypes[0]
}

func (x AnalyticsEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnalyticsEventType.Descriptor instead.
func (AnalyticsEventType) EnumDescriptor() ([]byte, []int) {
	return file_plugnmeet_analytics_proto_rawDescGZIP(), []int{0}
}

type AnalyticsEvents int32

const (
	AnalyticsEvents_ANALYTICS_EVENT_UNKNOWN AnalyticsEvents = 0
	// room related
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_POLL_ADDED AnalyticsEvents = 1
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_POLL_ENDED AnalyticsEvents = 2
	// user join will be room related
	// after take record it will pass to user
	AnalyticsEvents_ANALYTICS_EVENT_USER_JOINED AnalyticsEvents = 3
	// room recorder
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_RECORDING_STATUS                                AnalyticsEvents = 4
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_RTMP_STATUS                                     AnalyticsEvents = 5
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_BREAKOUT_ROOM                                   AnalyticsEvents = 6
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_ETHERPAD_STATUS                                 AnalyticsEvents = 7
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_EXTERNAL_DISPLAY_LINK_STATUS                    AnalyticsEvents = 8
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_EXTERNAL_MEDIA_PLAYER_STATUS                    AnalyticsEvents = 9
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_SPEECH_SERVICE_STATUS                           AnalyticsEvents = 10
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_SPEECH_SERVICE_TOTAL_USAGE                      AnalyticsEvents = 11
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_INGRESS_CREATED                                 AnalyticsEvents = 12
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_WHITEBOARD_FILES                                AnalyticsEvents = 13
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_INSIGHTS_TRANSCRIPTION_STATUS                   AnalyticsEvents = 31
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_INSIGHTS_TRANSCRIPTION_TOTAL_USAGE              AnalyticsEvents = 32
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_INSIGHTS_CHAT_TRANSLATION_STATUS                AnalyticsEvents = 33
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_INSIGHTS_CHAT_TRANSLATION_TOTAL_USAGE           AnalyticsEvents = 34
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_INSIGHTS_AI_TEXT_CHAT_STATUS                    AnalyticsEvents = 35
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_INSIGHTS_AI_TEXT_CHAT_INTERACTION_TOTAL_USAGE   AnalyticsEvents = 36
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_INSIGHTS_AI_TEXT_CHAT_SUMMARIZATION_TOTAL_USAGE AnalyticsEvents = 37
	AnalyticsEvents_ANALYTICS_EVENT_ROOM_INSIGHTS_AI_MEETING_SUMMARIZATION_STATUS        AnalyticsEvents = 38
	// here all related with user
	AnalyticsEvents_ANALYTICS_EVENT_USER_LEFT AnalyticsEvents = 14
	// microphone
	AnalyticsEvents_ANALYTICS_EVENT_USER_MIC_STATUS      AnalyticsEvents = 15
	AnalyticsEvents_ANALYTICS_EVENT_USER_TALKED          AnalyticsEvents = 16
	AnalyticsEvents_ANALYTICS_EVENT_USER_TALKED_DURATION AnalyticsEvents = 17 // in milliseconds
	// webcam
	AnalyticsEvents_ANALYTICS_EVENT_USER_WEBCAM_STATUS AnalyticsEvents = 18
	// screen share
	AnalyticsEvents_ANALYTICS_EVENT_USER_SCREEN_SHARE_STATUS AnalyticsEvents = 19
	// polls
	AnalyticsEvents_ANALYTICS_EVENT_USER_VOTED_POLL AnalyticsEvents = 20
	// chat
	AnalyticsEvents_ANALYTICS_EVENT_USER_PUBLIC_CHAT  AnalyticsEvents = 21
	AnalyticsEvents_ANALYTICS_EVENT_USER_PRIVATE_CHAT AnalyticsEvents = 22
	AnalyticsEvents_ANALYTICS_EVENT_USER_CHAT_FILES   AnalyticsEvents = 23
	// whiteboard
	AnalyticsEvents_ANALYTICS_EVENT_USER_WHITEBOARD_ANNOTATED AnalyticsEvents = 24
	AnalyticsEvents_ANALYTICS_EVENT_USER_WHITEBOARD_FILES     AnalyticsEvents = 25
	// speech services
	AnalyticsEvents_ANALYTICS_EVENT_USER_SPEECH_SERVICES_USAGE  AnalyticsEvents = 26
	AnalyticsEvents_ANALYTICS_EVENT_USER_SPEECH_SERVICES_STATUS AnalyticsEvents = 27
	// etc
	AnalyticsEvents_ANALYTICS_EVENT_USER_INTERFACE_VISIBILITY AnalyticsEvents = 28
	AnalyticsEvents_ANALYTICS_EVENT_USER_RAISE_HAND           AnalyticsEvents = 29
	AnalyticsEvents_ANALYTICS_EVENT_USER_CONNECTION_QUALITY   AnalyticsEvents = 30
)

// Enum value maps for AnalyticsEvents.
var (
	AnalyticsEvents_name = map[int32]string{
		0:  "ANALYTICS_EVENT_UNKNOWN",
		1:  "ANALYTICS_EVENT_ROOM_POLL_ADDED",
		2:  "ANALYTICS_EVENT_ROOM_POLL_ENDED",
		3:  "ANALYTICS_EVENT_USER_JOINED",
		4:  "ANALYTICS_EVENT_ROOM_RECORDING_STATUS",
		5:  "ANALYTICS_EVENT_ROOM_RTMP_STATUS",
		6:  "ANALYTICS_EVENT_ROOM_BREAKOUT_ROOM",
		7:  "ANALYTICS_EVENT_ROOM_ETHERPAD_STATUS",
		8:  "ANALYTICS_EVENT_ROOM_EXTERNAL_DISPLAY_LINK_STATUS",
		9:  "ANALYTICS_EVENT_ROOM_EXTERNAL_MEDIA_PLAYER_STATUS",
		10: "ANALYTICS_EVENT_ROOM_SPEECH_SERVICE_STATUS",
		11: "ANALYTICS_EVENT_ROOM_SPEECH_SERVICE_TOTAL_USAGE",
		12: "ANALYTICS_EVENT_ROOM_INGRESS_CREATED",
		13: "ANALYTICS_EVENT_ROOM_WHITEBOARD_FILES",
		31: "ANALYTICS_EVENT_ROOM_INSIGHTS_TRANSCRIPTION_STATUS",
		32: "ANALYTICS_EVENT_ROOM_INSIGHTS_TRANSCRIPTION_TOTAL_USAGE",
		33: "ANALYTICS_EVENT_ROOM_INSIGHTS_CHAT_TRANSLATION_STATUS",
		34: "ANALYTICS_EVENT_ROOM_INSIGHTS_CHAT_TRANSLATION_TOTAL_USAGE",
		35: "ANALYTICS_EVENT_ROOM_INSIGHTS_AI_TEXT_CHAT_STATUS",
		36: "ANALYTICS_EVENT_ROOM_INSIGHTS_AI_TEXT_CHAT_INTERACTION_TOTAL_USAGE",
		37: "ANALYTICS_EVENT_ROOM_INSIGHTS_AI_TEXT_CHAT_SUMMARIZATION_TOTAL_USAGE",
		38: "ANALYTICS_EVENT_ROOM_INSIGHTS_AI_MEETING_SUMMARIZATION_STATUS",
		14: "ANALYTICS_EVENT_USER_LEFT",
		15: "ANALYTICS_EVENT_USER_MIC_STATUS",
		16: "ANALYTICS_EVENT_USER_TALKED",
		17: "ANALYTICS_EVENT_USER_TALKED_DURATION",
		18: "ANALYTICS_EVENT_USER_WEBCAM_STATUS",
		19: "ANALYTICS_EVENT_USER_SCREEN_SHARE_STATUS",
		20: "ANALYTICS_EVENT_USER_VOTED_POLL",
		21: "ANALYTICS_EVENT_USER_PUBLIC_CHAT",
		22: "ANALYTICS_EVENT_USER_PRIVATE_CHAT",
		23: "ANALYTICS_EVENT_USER_CHAT_FILES",
		24: "ANALYTICS_EVENT_USER_WHITEBOARD_ANNOTATED",
		25: "ANALYTICS_EVENT_USER_WHITEBOARD_FILES",
		26: "ANALYTICS_EVENT_USER_SPEECH_SERVICES_USAGE",
		27: "ANALYTICS_EVENT_USER_SPEECH_SERVICES_STATUS",
		28: "ANALYTICS_EVENT_USER_INTERFACE_VISIBILITY",
		29: "ANALYTICS_EVENT_USER_RAISE_HAND",
		30: "ANALYTICS_EVENT_USER_CONNECTION_QUALITY",
	}
	AnalyticsEvents_value = map[string]int32{
		"ANALYTICS_EVENT_UNKNOWN":                                              0,
		"ANALYTICS_EVENT_ROOM_POLL_ADDED":                                      1,
		"ANALYTICS_EVENT_ROOM_POLL_ENDED":                                      2,
		"ANALYTICS_EVENT_USER_JOINED":                                          3,
		"ANALYTICS_EVENT_ROOM_RECORDING_STATUS":                                4,
		"ANALYTICS_EVENT_ROOM_RTMP_STATUS":                                     5,
		"ANALYTICS_EVENT_ROOM_BREAKOUT_ROOM":                                   6,
		"ANALYTICS_EVENT_ROOM_ETHERPAD_STATUS":                                 7,
		"ANALYTICS_EVENT_ROOM_EXTERNAL_DISPLAY_LINK_STATUS":                    8,
		"ANALYTICS_EVENT_ROOM_EXTERNAL_MEDIA_PLAYER_STATUS":                    9,
		"ANALYTICS_EVENT_ROOM_SPEECH_SERVICE_STATUS":                           10,
		"ANALYTICS_EVENT_ROOM_SPEECH_SERVICE_TOTAL_USAGE":                      11,
		"ANALYTICS_EVENT_ROOM_INGRESS_CREATED":                                 12,
		"ANALYTICS_EVENT_ROOM_WHITEBOARD_FILES":                                13,
		"ANALYTICS_EVENT_ROOM_INSIGHTS_TRANSCRIPTION_STATUS":                   31,
		"ANALYTICS_EVENT_ROOM_INSIGHTS_TRANSCRIPTION_TOTAL_USAGE":              32,
		"ANALYTICS_EVENT_ROOM_INSIGHTS_CHAT_TRANSLATION_STATUS":                33,
		"ANALYTICS_EVENT_ROOM_INSIGHTS_CHAT_TRANSLATION_TOTAL_USAGE":           34,
		"ANALYTICS_EVENT_ROOM_INSIGHTS_AI_TEXT_CHAT_STATUS":                    35,
		"ANALYTICS_EVENT_ROOM_INSIGHTS_AI_TEXT_CHAT_INTERACTION_TOTAL_USAGE":   36,
		"ANALYTICS_EVENT_ROOM_INSIGHTS_AI_TEXT_CHAT_SUMMARIZATION_TOTAL_USAGE": 37,
		"ANALYTICS_EVENT_ROOM_INSIGHTS_AI_MEETING_SUMMARIZATION_STATUS":        38,
		"ANALYTICS_EVENT_USER_LEFT":                                            14,
		"ANALYTICS_EVENT_USER_MIC_STATUS":                                      15,
		"ANALYTICS_EVENT_USER_TALKED":                                          16,
		"ANALYTICS_EVENT_USER_TALKED_DURATION":                                 17,
		"ANALYTICS_EVENT_USER_WEBCAM_STATUS":                                   18,
		"ANALYTICS_EVENT_USER_SCREEN_SHARE_STATUS":                             19,
		"ANALYTICS_EVENT_USER_VOTED_POLL":                                      20,
		"ANALYTICS_EVENT_USER_PUBLIC_CHAT":                                     21,
		"ANALYTICS_EVENT_USER_PRIVATE_CHAT":                                    22,
		"ANALYTICS_EVENT_USER_CHAT_FILES":                                      23,
		"ANALYTICS_EVENT_USER_WHITEBOARD_ANNOTATED":                            24,
		"ANALYTICS_EVENT_USER_WHITEBOARD_FILES":                                25,
		"ANALYTICS_EVENT_USER_SPEECH_SERVICES_USAGE":                           26,
		"ANALYTICS_EVENT_USER_SPEECH_SERVICES_STATUS":                          27,
		"ANALYTICS_EVENT_USER_INTERFACE_VISIBILITY":                            28,
		"ANALYTICS_EVENT_USER_RAISE_HAND":                                      29,
		"ANALYTICS_EVENT_USER_CONNECTION_QUALITY":                              30,
	}
)

func (x AnalyticsEvents) Enum() *AnalyticsEvents {
	p := new(AnalyticsEvents)
	*p = x
	return p
}

func (x AnalyticsEvents) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnalyticsEvents) Descriptor() protoreflect.EnumDescriptor {
	return file_plugnmeet_analytics_proto_enumTypes[1].Descriptor()
}

func (AnalyticsEvents) Type() protoreflect.EnumType {
	return &file_plugnmeet_analytics_proto_enumTypes[1]
}

func (x AnalyticsEvents) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnalyticsEvents.Descriptor instead.
func (AnalyticsEvents) EnumDescriptor() ([]byte, []int) {
	return file_plugnmeet_analytics_proto_rawDescGZIP(), []int{1}
}

type AnalyticsStatus int32

const (
	AnalyticsStatus_ANALYTICS_STATUS_STARTED AnalyticsStatus = 0
	AnalyticsStatus_ANALYTICS_STATUS_ENDED   AnalyticsStatus = 1
	AnalyticsStatus_ANALYTICS_STATUS_MUTED   AnalyticsStatus = 2
	AnalyticsStatus_ANALYTICS_STATUS_UNMUTED AnalyticsStatus = 3
)

// Enum value maps for AnalyticsStatus.
var (
	AnalyticsStatus_name = map[int32]string{
		0: "ANALYTICS_STATUS_STARTED",
		1: "ANALYTICS_STATUS_ENDED",
		2: "ANALYTICS_STATUS_MUTED",
		3: "ANALYTICS_STATUS_UNMUTED",
	}
	AnalyticsStatus_value = map[string]int32{
		"ANALYTICS_STATUS_STARTED": 0,
		"ANALYTICS_STATUS_ENDED":   1,
		"ANALYTICS_STATUS_MUTED":   2,
		"ANALYTICS_STATUS_UNMUTED": 3,
	}
)

func (x AnalyticsStatus) Enum() *AnalyticsStatus {
	p := new(AnalyticsStatus)
	*p = x
	return p
}

func (x AnalyticsStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnalyticsStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_plugnmeet_analytics_proto_enumTypes[2].Descriptor()
}

func (AnalyticsStatus) Type() protoreflect.EnumType {
	return &file_plugnmeet_analytics_proto_enumTypes[2]
}

func (x AnalyticsStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnalyticsStatus.Descriptor instead.
func (AnalyticsStatus) EnumDescriptor() ([]byte, []int) {
	return file_plugnmeet_analytics_proto_rawDescGZIP(), []int{2}
}

type AnalyticsDataMsg struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventType AnalyticsEventType     `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=plugnmeet.AnalyticsEventType" json:"event_type,omitempty"`
	EventName AnalyticsEvents        `protobuf:"varint,2,opt,name=event_name,json=eventName,proto3,enum=plugnmeet.AnalyticsEvents" json:"event_name,omitempty"`
	RoomId    string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// should be unix milliseconds
	Time int64 `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	// if we pass value here then it will use redis SET to set the value for the key
	EventValueString *string `protobuf:"bytes,5,opt,name=event_value_string,json=eventValueString,proto3,oneof" json:"event_value_string,omitempty"`
	// if we pass value here then it will use redis INCRBY to increment value for the key
	EventValueInteger *int64 `protobuf:"varint,6,opt,name=event_value_integer,json=eventValueInteger,proto3,oneof" json:"event_value_integer,omitempty"`
	// if we pass value here then it will use redis HSET to set hash field value for the key
	// hash field will be unix milliseconds, so it will remain unique as always
	HsetValue *string `protobuf:"bytes,7,opt,name=hset_value,json=hsetValue,proto3,oneof" json:"hset_value,omitempty"`
	RoomSid   *string `protobuf:"bytes,8,opt,name=room_sid,json=roomSid,proto3,oneof" json:"room_sid,omitempty"`
	UserId    *string `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	UserName  *string `protobuf:"bytes,10,opt,name=user_name,json=userName,proto3,oneof" json:"user_name,omitempty"`
	// this extra_data can be use for various purposes like, room or user metadata
	ExtraData     *string `protobuf:"bytes,11,opt,name=extra_data,json=extraData,proto3,oneof" json:"extra_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsDataMsg) Reset() {
	*x = AnalyticsDataMsg{}
	mi := &file_plugnmeet_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsDataMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsDataMsg) ProtoMessage() {}

func (x *AnalyticsDataMsg) ProtoReflect() protoreflect.Message {
	mi := &file_plugnmeet_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsDataMsg.ProtoReflect.Descriptor instead.
func (*AnalyticsDataMsg) Descriptor() ([]byte, []int) {
	return file_plugnmeet_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyticsDataMsg) GetEventType() AnalyticsEventType {
	if x != nil {
		return x.EventType
	}
	return AnalyticsEventType_ANALYTICS_EVENT_TYPE_ROOM
}

func (x *AnalyticsDataMsg) GetEventName() AnalyticsEvents {
	if x != nil {
		return x.EventName
	}
	return AnalyticsEvents_ANALYTICS_EVENT_UNKNOWN
}

func (x *AnalyticsDataMsg) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AnalyticsDataMsg) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *AnalyticsDataMsg) GetEventValueString() string {
	if x != nil && x.EventValueString != nil {
		return *x.EventValueString
	}
	return ""
}

func (x *AnalyticsDataMsg) GetEventValueInteger() int64 {
	if x != nil && x.EventValueInteger != nil {
		return *x.EventValueInteger
	}
	return 0
}

func (x *AnalyticsDataMsg) GetHsetValue() string {
	if x != nil && x.HsetValue != nil {
		return *x.HsetValue
	}
	return ""
}

func (x *AnalyticsDataMsg) GetRoomSid() string {
	if x != nil && x.RoomSid != nil {
		return *x.RoomSid
	}
	return ""
}

func (x *AnalyticsDataMsg) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *AnalyticsDataMsg) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *AnalyticsDataMsg) GetExtraData() string {
	if x != nil && x.ExtraData != nil {
		return *x.ExtraData
	}
	return ""
}

type AnalyticsEventValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsEventValue) Reset() {
	*x = AnalyticsEventValue{}
	mi := &file_plugnmeet_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsEventValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsEventValue) ProtoMessage() {}

func (x *AnalyticsEventValue) ProtoReflect() protoreflect.Message {
	mi := &file_plugnmeet_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsEventValue.ProtoReflect.Descriptor instead.
func (*AnalyticsEventValue) Descriptor() ([]byte, []int) {
	return file_plugnmeet_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyticsEventValue) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *AnalyticsEventValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AnalyticsEventData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Values        []*AnalyticsEventValue `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsEventData) Reset() {
	*x = AnalyticsEventData{}
	mi := &file_plugnmeet_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsEventData) ProtoMessage() {}

func (x *AnalyticsEventData) ProtoReflect() protoreflect.Message {
	mi := &file_plugnmeet_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsEventData.ProtoReflect.Descriptor instead.
func (*AnalyticsEventData) Descriptor() ([]byte, []int) {
	return file_plugnmeet_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyticsEventData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnalyticsEventData) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AnalyticsEventData) GetValues() []*AnalyticsEventValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type AnalyticsRoomInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomTitle      string                 `protobuf:"bytes,2,opt,name=room_title,json=roomTitle,proto3" json:"room_title,omitempty"`
	RoomTotalUsers int64                  `protobuf:"varint,3,opt,name=room_total_users,json=roomTotalUsers,proto3" json:"room_total_users,omitempty"`
	RoomCreation   int64                  `protobuf:"varint,4,opt,name=room_creation,json=roomCreation,proto3" json:"room_creation,omitempty"`
	RoomEnded      int64                  `protobuf:"varint,5,opt,name=room_ended,json=roomEnded,proto3" json:"room_ended,omitempty"`
	RoomDuration   int64                  `protobuf:"varint,6,opt,name=room_duration,json=roomDuration,proto3" json:"room_duration,omitempty"`
	EnabledE2Ee    bool                   `protobuf:"varint,7,opt,name=enabled_e2ee,json=enabledE2ee,proto3" json:"enabled_e2ee,omitempty"`
	Events         []*AnalyticsEventData  `protobuf:"bytes,9,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyticsRoomInfo) Reset() {
	*x = AnalyticsRoomInfo{}
	mi := &file_plugnmeet_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsRoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsRoomInfo) ProtoMessage() {}

func (x *AnalyticsRoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugnmeet_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsRoomInfo.ProtoReflect.Descriptor instead.
func (*AnalyticsRoomInfo) Descriptor() ([]byte, []int) {
	return file_plugnmeet_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *AnalyticsRoomInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AnalyticsRoomInfo) GetRoomTitle() string {
	if x != nil {
		return x.RoomTitle
	}
	return ""
}

func (x *AnalyticsRoomInfo) GetRoomTotalUsers() int64 {
	if x != nil {
		return x.RoomTotalUsers
	}
	return 0
}

func (x *AnalyticsRoomInfo) GetRoomCreation() int64 {
	if x != nil {
		return x.RoomCreation
	}
	return 0
}

func (x *AnalyticsRoomInfo) GetRoomEnded() int64 {
	if x != nil {
		return x.RoomEnded
	}
	return 0
}

func (x *AnalyticsRoomInfo) GetRoomDuration() int64 {
	if x != nil {
		return x.RoomDuration
	}
	return 0
}

func (x *AnalyticsRoomInfo) GetEnabledE2Ee() bool {
	if x != nil {
		return x.EnabledE2Ee
	}
	return false
}

func (x *AnalyticsRoomInfo) GetEvents() []*AnalyticsEventData {
	if x != nil {
		return x.Events
	}
	return nil
}

type AnalyticsUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	ExtraData     *string                `protobuf:"bytes,4,opt,name=extra_data,json=extraData,proto3,oneof" json:"extra_data,omitempty"`
	ExUserId      *string                `protobuf:"bytes,5,opt,name=ex_user_id,json=exUserId,proto3,oneof" json:"ex_user_id,omitempty"`
	Events        []*AnalyticsEventData  `protobuf:"bytes,6,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsUserInfo) Reset() {
	*x = AnalyticsUserInfo{}
	mi := &file_plugnmeet_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsUserInfo) ProtoMessage() {}

func (x *AnalyticsUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugnmeet_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsUserInfo.ProtoReflect.Descriptor instead.
func (*AnalyticsUserInfo) Descriptor() ([]byte, []int) {
	return file_plugnmeet_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *AnalyticsUserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AnalyticsUserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnalyticsUserInfo) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *AnalyticsUserInfo) GetExtraData() string {
	if x != nil && x.ExtraData != nil {
		return *x.ExtraData
	}
	return ""
}

func (x *AnalyticsUserInfo) GetExUserId() string {
	if x != nil && x.ExUserId != nil {
		return *x.ExUserId
	}
	return ""
}

func (x *AnalyticsUserInfo) GetEvents() []*AnalyticsEventData {
	if x != nil {
		return x.Events
	}
	return nil
}

type AnalyticsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *AnalyticsRoomInfo     `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Users         []*AnalyticsUserInfo   `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsResult) Reset() {
	*x = AnalyticsResult{}
	mi := &file_plugnmeet_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsResult) ProtoMessage() {}

func (x *AnalyticsResult) ProtoReflect() protoreflect.Message {
	mi := &file_plugnmeet_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsResult.ProtoReflect.Descriptor instead.
func (*AnalyticsResult) Descriptor() ([]byte, []int) {
	return file_plugnmeet_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *AnalyticsResult) GetRoom() *AnalyticsRoomInfo {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *AnalyticsResult) GetUsers() []*AnalyticsUserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type AnalyticsRedisUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,2,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	ExtraData     *string                `protobuf:"bytes,3,opt,name=extra_data,json=extraData,proto3,oneof" json:"extra_data,omitempty"`
	ExUserId      *string                `protobuf:"bytes,4,opt,name=ex_user_id,json=exUserId,proto3,oneof" json:"ex_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsRedisUserInfo) Reset() {
	*x = AnalyticsRedisUserInfo{}
	mi := &file_plugnmeet_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsRedisUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsRedisUserInfo) ProtoMessage() {}

func (x *AnalyticsRedisUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugnmeet_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsRedisUserInfo.ProtoReflect.Descriptor instead.
func (*AnalyticsRedisUserInfo) Descriptor() ([]byte, []int) {
	return file_plugnmeet_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *AnalyticsRedisUserInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *AnalyticsRedisUserInfo) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *AnalyticsRedisUserInfo) GetExtraData() string {
	if x != nil && x.ExtraData != nil {
		return *x.ExtraData
	}
	return ""
}

func (x *AnalyticsRedisUserInfo) GetExUserId() string {
	if x != nil && x.ExUserId != nil {
		return *x.ExUserId
	}
	return ""
}

var File_plugnmeet_analytics_proto protoreflect.FileDescriptor

const file_plugnmeet_analytics_proto_rawDesc = "" +
	"\n" +
	"\x19plugnmeet_analytics.proto\x12\tplugnmeet\"\xbc\x04\n" +
	"\x10AnalyticsDataMsg\x12<\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2\x1d.plugnmeet.AnalyticsEventTypeR\teventType\x129\n" +
	"\n" +
	"event_name\x18\x02 \x01(\x0e2\x1a.plugnmeet.AnalyticsEventsR\teventName\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x03R\x04time\x121\n" +
	"\x12event_value_string\x18\x05 \x01(\tH\x00R\x10eventValueString\x88\x01\x01\x123\n" +
	"\x13event_value_integer\x18\x06 \x01(\x03H\x01R\x11eventValueInteger\x88\x01\x01\x12\"\n" +
	"\n" +
	"hset_value\x18\a \x01(\tH\x02R\thsetValue\x88\x01\x01\x12\x1e\n" +
	"\broom_sid\x18\b \x01(\tH\x03R\aroomSid\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\t \x01(\tH\x04R\x06userId\x88\x01\x01\x12 \n" +
	"\tuser_name\x18\n" +
	" \x01(\tH\x05R\buserName\x88\x01\x01\x12\"\n" +
	"\n" +
	"extra_data\x18\v \x01(\tH\x06R\textraData\x88\x01\x01B\x15\n" +
	"\x13_event_value_stringB\x16\n" +
	"\x14_event_value_integerB\r\n" +
	"\v_hset_valueB\v\n" +
	"\t_room_sidB\n" +
	"\n" +
	"\b_user_idB\f\n" +
	"\n" +
	"_user_nameB\r\n" +
	"\v_extra_data\"?\n" +
	"\x13AnalyticsEventValue\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"v\n" +
	"\x12AnalyticsEventData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x126\n" +
	"\x06values\x18\x03 \x03(\v2\x1e.plugnmeet.AnalyticsEventValueR\x06values\"\xb8\x02\n" +
	"\x11AnalyticsRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"room_title\x18\x02 \x01(\tR\troomTitle\x12(\n" +
	"\x10room_total_users\x18\x03 \x01(\x03R\x0eroomTotalUsers\x12#\n" +
	"\rroom_creation\x18\x04 \x01(\x03R\froomCreation\x12\x1d\n" +
	"\n" +
	"room_ended\x18\x05 \x01(\x03R\troomEnded\x12#\n" +
	"\rroom_duration\x18\x06 \x01(\x03R\froomDuration\x12!\n" +
	"\fenabled_e2ee\x18\a \x01(\bR\venabledE2ee\x125\n" +
	"\x06events\x18\t \x03(\v2\x1d.plugnmeet.AnalyticsEventDataR\x06events\"\xf7\x01\n" +
	"\x11AnalyticsUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bis_admin\x18\x03 \x01(\bR\aisAdmin\x12\"\n" +
	"\n" +
	"extra_data\x18\x04 \x01(\tH\x00R\textraData\x88\x01\x01\x12!\n" +
	"\n" +
	"ex_user_id\x18\x05 \x01(\tH\x01R\bexUserId\x88\x01\x01\x125\n" +
	"\x06events\x18\x06 \x03(\v2\x1d.plugnmeet.AnalyticsEventDataR\x06eventsB\r\n" +
	"\v_extra_dataB\r\n" +
	"\v_ex_user_id\"w\n" +
	"\x0fAnalyticsResult\x120\n" +
	"\x04room\x18\x01 \x01(\v2\x1c.plugnmeet.AnalyticsRoomInfoR\x04room\x122\n" +
	"\x05users\x18\x02 \x03(\v2\x1c.plugnmeet.AnalyticsUserInfoR\x05users\"\xba\x01\n" +
	"\x16AnalyticsRedisUserInfo\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\bis_admin\x18\x02 \x01(\bR\aisAdmin\x12\"\n" +
	"\n" +
	"extra_data\x18\x03 \x01(\tH\x01R\textraData\x88\x01\x01\x12!\n" +
	"\n" +
	"ex_user_id\x18\x04 \x01(\tH\x02R\bexUserId\x88\x01\x01B\a\n" +
	"\x05_nameB\r\n" +
	"\v_extra_dataB\r\n" +
	"\v_ex_user_id*R\n" +
	"\x12AnalyticsEventType\x12\x1d\n" +
	"\x19ANALYTICS_EVENT_TYPE_ROOM\x10\x00\x12\x1d\n" +
	"\x19ANALYTICS_EVENT_TYPE_USER\x10\x01*\x98\x0e\n" +
	"\x0fAnalyticsEvents\x12\x1b\n" +
	"\x17ANALYTICS_EVENT_UNKNOWN\x10\x00\x12#\n" +
	"\x1fANALYTICS_EVENT_ROOM_POLL_ADDED\x10\x01\x12#\n" +
	"\x1fANALYTICS_EVENT_ROOM_POLL_ENDED\x10\x02\x12\x1f\n" +
	"\x1bANALYTICS_EVENT_USER_JOINED\x10\x03\x12)\n" +
	"%ANALYTICS_EVENT_ROOM_RECORDING_STATUS\x10\x04\x12$\n" +
	" ANALYTICS_EVENT_ROOM_RTMP_STATUS\x10\x05\x12&\n" +
	"\"ANALYTICS_EVENT_ROOM_BREAKOUT_ROOM\x10\x06\x12(\n" +
	"$ANALYTICS_EVENT_ROOM_ETHERPAD_STATUS\x10\a\x125\n" +
	"1ANALYTICS_EVENT_ROOM_EXTERNAL_DISPLAY_LINK_STATUS\x10\b\x125\n" +
	"1ANALYTICS_EVENT_ROOM_EXTERNAL_MEDIA_PLAYER_STATUS\x10\t\x12.\n" +
	"*ANALYTICS_EVENT_ROOM_SPEECH_SERVICE_STATUS\x10\n" +
	"\x123\n" +
	"/ANALYTICS_EVENT_ROOM_SPEECH_SERVICE_TOTAL_USAGE\x10\v\x12(\n" +
	"$ANALYTICS_EVENT_ROOM_INGRESS_CREATED\x10\f\x12)\n" +
	"%ANALYTICS_EVENT_ROOM_WHITEBOARD_FILES\x10\r\x126\n" +
	"2ANALYTICS_EVENT_ROOM_INSIGHTS_TRANSCRIPTION_STATUS\x10\x1f\x12;\n" +
	"7ANALYTICS_EVENT_ROOM_INSIGHTS_TRANSCRIPTION_TOTAL_USAGE\x10 \x129\n" +
	"5ANALYTICS_EVENT_ROOM_INSIGHTS_CHAT_TRANSLATION_STATUS\x10!\x12>\n" +
	":ANALYTICS_EVENT_ROOM_INSIGHTS_CHAT_TRANSLATION_TOTAL_USAGE\x10\"\x125\n" +
	"1ANALYTICS_EVENT_ROOM_INSIGHTS_AI_TEXT_CHAT_STATUS\x10#\x12F\n" +
	"BANALYTICS_EVENT_ROOM_INSIGHTS_AI_TEXT_CHAT_INTERACTION_TOTAL_USAGE\x10$\x12H\n" +
	"DANALYTICS_EVENT_ROOM_INSIGHTS_AI_TEXT_CHAT_SUMMARIZATION_TOTAL_USAGE\x10%\x12A\n" +
	"=ANALYTICS_EVENT_ROOM_INSIGHTS_AI_MEETING_SUMMARIZATION_STATUS\x10&\x12\x1d\n" +
	"\x19ANALYTICS_EVENT_USER_LEFT\x10\x0e\x12#\n" +
	"\x1fANALYTICS_EVENT_USER_MIC_STATUS\x10\x0f\x12\x1f\n" +
	"\x1bANALYTICS_EVENT_USER_TALKED\x10\x10\x12(\n" +
	"$ANALYTICS_EVENT_USER_TALKED_DURATION\x10\x11\x12&\n" +
	"\"ANALYTICS_EVENT_USER_WEBCAM_STATUS\x10\x12\x12,\n" +
	"(ANALYTICS_EVENT_USER_SCREEN_SHARE_STATUS\x10\x13\x12#\n" +
	"\x1fANALYTICS_EVENT_USER_VOTED_POLL\x10\x14\x12$\n" +
	" ANALYTICS_EVENT_USER_PUBLIC_CHAT\x10\x15\x12%\n" +
	"!ANALYTICS_EVENT_USER_PRIVATE_CHAT\x10\x16\x12#\n" +
	"\x1fANALYTICS_EVENT_USER_CHAT_FILES\x10\x17\x12-\n" +
	")ANALYTICS_EVENT_USER_WHITEBOARD_ANNOTATED\x10\x18\x12)\n" +
	"%ANALYTICS_EVENT_USER_WHITEBOARD_FILES\x10\x19\x12.\n" +
	"*ANALYTICS_EVENT_USER_SPEECH_SERVICES_USAGE\x10\x1a\x12/\n" +
	"+ANALYTICS_EVENT_USER_SPEECH_SERVICES_STATUS\x10\x1b\x12-\n" +
	")ANALYTICS_EVENT_USER_INTERFACE_VISIBILITY\x10\x1c\x12#\n" +
	"\x1fANALYTICS_EVENT_USER_RAISE_HAND\x10\x1d\x12+\n" +
	"'ANALYTICS_EVENT_USER_CONNECTION_QUALITY\x10\x1e*\x85\x01\n" +
	"\x0fAnalyticsStatus\x12\x1c\n" +
	"\x18ANALYTICS_STATUS_STARTED\x10\x00\x12\x1a\n" +
	"\x16ANALYTICS_STATUS_ENDED\x10\x01\x12\x1a\n" +
	"\x16ANALYTICS_STATUS_MUTED\x10\x02\x12\x1c\n" +
	"\x18ANALYTICS_STATUS_UNMUTED\x10\x03B\xa0\x01\n" +
	"\rcom.plugnmeetB\x17PlugnmeetAnalyticsProtoP\x01Z2github.com/mynaparrot/plugnmeet-protocol/plugnmeet\xa2\x02\x03PXX\xaa\x02\tPlugnmeet\xca\x02\tPlugnmeet\xe2\x02\x15Plugnmeet\\GPBMetadata\xea\x02\tPlugnmeetb\x06proto3"

var (
	file_plugnmeet_analytics_proto_rawDescOnce sync.Once
	file_plugnmeet_analytics_proto_rawDescData []byte
)

func file_plugnmeet_analytics_proto_rawDescGZIP() []byte {
	file_plugnmeet_analytics_proto_rawDescOnce.Do(func() {
		file_plugnmeet_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugnmeet_analytics_proto_rawDesc), len(file_plugnmeet_analytics_proto_rawDesc)))
	})
	return file_plugnmeet_analytics_proto_rawDescData
}

var file_plugnmeet_analytics_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_plugnmeet_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_plugnmeet_analytics_proto_goTypes = []any{
	(AnalyticsEventType)(0),        // 0: plugnmeet.AnalyticsEventType
	(AnalyticsEvents)(0),           // 1: plugnmeet.AnalyticsEvents
	(AnalyticsStatus)(0),           // 2: plugnmeet.AnalyticsStatus
	(*AnalyticsDataMsg)(nil),       // 3: plugnmeet.AnalyticsDataMsg
	(*AnalyticsEventValue)(nil),    // 4: plugnmeet.AnalyticsEventValue
	(*AnalyticsEventData)(nil),     // 5: plugnmeet.AnalyticsEventData
	(*AnalyticsRoomInfo)(nil),      // 6: plugnmeet.AnalyticsRoomInfo
	(*AnalyticsUserInfo)(nil),      // 7: plugnmeet.AnalyticsUserInfo
	(*AnalyticsResult)(nil),        // 8: plugnmeet.AnalyticsResult
	(*AnalyticsRedisUserInfo)(nil), // 9: plugnmeet.AnalyticsRedisUserInfo
}
var file_plugnmeet_analytics_proto_depIdxs = []int32{
	0, // 0: plugnmeet.AnalyticsDataMsg.event_type:type_name -> plugnmeet.AnalyticsEventType
	1, // 1: plugnmeet.AnalyticsDataMsg.event_name:type_name -> plugnmeet.AnalyticsEvents
	4, // 2: plugnmeet.AnalyticsEventData.values:type_name -> plugnmeet.AnalyticsEventValue
	5, // 3: plugnmeet.AnalyticsRoomInfo.events:type_name -> plugnmeet.AnalyticsEventData
	5, // 4: plugnmeet.AnalyticsUserInfo.events:type_name -> plugnmeet.AnalyticsEventData
	6, // 5: plugnmeet.AnalyticsResult.room:type_name -> plugnmeet.AnalyticsRoomInfo
	7, // 6: plugnmeet.AnalyticsResult.users:type_name -> plugnmeet.AnalyticsUserInfo
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_plugnmeet_analytics_proto_init() }
func file_plugnmeet_analytics_proto_init() {
	if File_plugnmeet_analytics_proto != nil {
		return
	}
	file_plugnmeet_analytics_proto_msgTypes[0].OneofWrappers = []any{}
	file_plugnmeet_analytics_proto_msgTypes[4].OneofWrappers = []any{}
	file_plugnmeet_analytics_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugnmeet_analytics_proto_rawDesc), len(file_plugnmeet_analytics_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugnmeet_analytics_proto_goTypes,
		DependencyIndexes: file_plugnmeet_analytics_proto_depIdxs,
		EnumInfos:         file_plugnmeet_analytics_proto_enumTypes,
		MessageInfos:      file_plugnmeet_analytics_proto_msgTypes,
	}.Build()
	File_plugnmeet_analytics_proto = out.File
	file_plugnmeet_analytics_proto_goTypes = nil
	file_plugnmeet_analytics_proto_depIdxs = nil
}
