// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: plugnmeet_lti_v1.proto

package plugnmeet

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on LtiClaims with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LtiClaims) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LtiClaims with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LtiClaimsMultiError, or nil
// if none found.
func (m *LtiClaims) ValidateAll() error {
	return m.validate(true)
}

func (m *LtiClaims) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Name

	// no validation rules for IsAdmin

	// no validation rules for RoomId

	// no validation rules for RoomTitle

	if all {
		switch v := interface{}(m.GetLtiCustomParameters()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LtiClaimsValidationError{
					field:  "LtiCustomParameters",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LtiClaimsValidationError{
					field:  "LtiCustomParameters",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLtiCustomParameters()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LtiClaimsValidationError{
				field:  "LtiCustomParameters",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return LtiClaimsMultiError(errors)
	}

	return nil
}

// LtiClaimsMultiError is an error wrapping multiple validation errors returned
// by LtiClaims.ValidateAll() if the designated constraints aren't met.
type LtiClaimsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LtiClaimsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LtiClaimsMultiError) AllErrors() []error { return m }

// LtiClaimsValidationError is the validation error returned by
// LtiClaims.Validate if the designated constraints aren't met.
type LtiClaimsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LtiClaimsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LtiClaimsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LtiClaimsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LtiClaimsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LtiClaimsValidationError) ErrorName() string { return "LtiClaimsValidationError" }

// Error satisfies the builtin error interface
func (e LtiClaimsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLtiClaims.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LtiClaimsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LtiClaimsValidationError{}

// Validate checks the field values on LtiCustomParameters with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *LtiCustomParameters) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LtiCustomParameters with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LtiCustomParametersMultiError, or nil if none found.
func (m *LtiCustomParameters) ValidateAll() error {
	return m.validate(true)
}

func (m *LtiCustomParameters) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetLtiCustomDesign()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LtiCustomParametersValidationError{
					field:  "LtiCustomDesign",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LtiCustomParametersValidationError{
					field:  "LtiCustomDesign",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLtiCustomDesign()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LtiCustomParametersValidationError{
				field:  "LtiCustomDesign",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.RoomDuration != nil {
		// no validation rules for RoomDuration
	}

	if m.AllowPolls != nil {
		// no validation rules for AllowPolls
	}

	if m.AllowSharedNotePad != nil {
		// no validation rules for AllowSharedNotePad
	}

	if m.AllowBreakoutRoom != nil {
		// no validation rules for AllowBreakoutRoom
	}

	if m.AllowRecording != nil {
		// no validation rules for AllowRecording
	}

	if m.AllowRtmp != nil {
		// no validation rules for AllowRtmp
	}

	if m.AllowViewOtherWebcams != nil {
		// no validation rules for AllowViewOtherWebcams
	}

	if m.AllowViewOtherUsersList != nil {
		// no validation rules for AllowViewOtherUsersList
	}

	if m.MuteOnStart != nil {
		// no validation rules for MuteOnStart
	}

	if len(errors) > 0 {
		return LtiCustomParametersMultiError(errors)
	}

	return nil
}

// LtiCustomParametersMultiError is an error wrapping multiple validation
// errors returned by LtiCustomParameters.ValidateAll() if the designated
// constraints aren't met.
type LtiCustomParametersMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LtiCustomParametersMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LtiCustomParametersMultiError) AllErrors() []error { return m }

// LtiCustomParametersValidationError is the validation error returned by
// LtiCustomParameters.Validate if the designated constraints aren't met.
type LtiCustomParametersValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LtiCustomParametersValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LtiCustomParametersValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LtiCustomParametersValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LtiCustomParametersValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LtiCustomParametersValidationError) ErrorName() string {
	return "LtiCustomParametersValidationError"
}

// Error satisfies the builtin error interface
func (e LtiCustomParametersValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLtiCustomParameters.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LtiCustomParametersValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LtiCustomParametersValidationError{}

// Validate checks the field values on LtiCustomDesign with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *LtiCustomDesign) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LtiCustomDesign with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LtiCustomDesignMultiError, or nil if none found.
func (m *LtiCustomDesign) ValidateAll() error {
	return m.validate(true)
}

func (m *LtiCustomDesign) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.PrimaryColor != nil {
		// no validation rules for PrimaryColor
	}

	if m.SecondaryColor != nil {
		// no validation rules for SecondaryColor
	}

	if m.BackgroundColor != nil {
		// no validation rules for BackgroundColor
	}

	if m.CustomLogo != nil {
		// no validation rules for CustomLogo
	}

	if len(errors) > 0 {
		return LtiCustomDesignMultiError(errors)
	}

	return nil
}

// LtiCustomDesignMultiError is an error wrapping multiple validation errors
// returned by LtiCustomDesign.ValidateAll() if the designated constraints
// aren't met.
type LtiCustomDesignMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LtiCustomDesignMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LtiCustomDesignMultiError) AllErrors() []error { return m }

// LtiCustomDesignValidationError is the validation error returned by
// LtiCustomDesign.Validate if the designated constraints aren't met.
type LtiCustomDesignValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LtiCustomDesignValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LtiCustomDesignValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LtiCustomDesignValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LtiCustomDesignValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LtiCustomDesignValidationError) ErrorName() string { return "LtiCustomDesignValidationError" }

// Error satisfies the builtin error interface
func (e LtiCustomDesignValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLtiCustomDesign.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LtiCustomDesignValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LtiCustomDesignValidationError{}
