name: Publish npm beta from nb branch

on:
  push:
    branches:
      - nb

permissions:
  id-token: write
  contents: write

jobs:
  publish-npm-beta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # This is needed to push the version bump
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1
        with:
          version: latest

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8

      - name: Build and publish beta
        run: |
          bash generate.sh
          cd js
          
          # This will create a version like x.y.z-beta.0, x.y.z-beta.1 and so on
          pnpm version prerelease --no-commit-hooks --no-git-tag-version
          
          # push changes back to the branch
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(beta): bump version for nb branch"
          git push
          
          bash generate.sh
          npm install -g npm@latest
          npm publish --tag beta --provenance
